### ISSUE TITLE
Builds related data should be stored in artifacts instead of custom data storage

### ISSUE THREAD

**Issue by pavelsher** [jpfeffer/teamcity-highlighter#1]
Plugin uses custom data storage associated with build type to store data for each build. Unfortunately custom data storage is not designed for storing lots of data and this approach can cause performance problems in the future. It would be more robust and faster to store data under the build artifacts, in .teamcity/<plugin name> directory.

**Comment by jpfeffer** [comment]
Thanks for the info, Pavel. I will update the implementation...

**Comment by jpfeffer** [comment]
Issue fixed by adding MySQL DB support as data storage
